#person配置类
person:
  name: chendong
  age: 27
  lists: [ cat,dog,person ]
  lists1:
    - cat
    - dog
    - person
  maps: { k1: v1,k2: v2 }
  dog:
    name: xiaohuang

#debug模式
debug: false

#默认服务端口号
server:
  port: 8080

#日志级别
logging:
  level:
    root: info

#mybatis配置
mybatis:
  type-aliases-package: com.chendong.demo.dao
  mapper-locations: classpath:mapper/*Mapper.xml
  #驼峰映射
  configuration:
    map-underscore-to-camel-case: true

#mysql配置
spring:
  #环境配置
  profiles:
    active: dev

    #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/xinyang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

---
#开发环境配置
server:
  port: 9081
spring:
  profiles: dev

---
#测试环境配置
server:
  port: 8082
spring:
  profiles: test