server:
  port: 8080
magic-api:
  #配置web页面入口
  web: /magic/web
  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
    location: D:/data/magic-api

#apollo配置
app:
  id: demo-9527
apollo:
  meta: http://apollodev.unisoc.com/config/
  bootstrap:
    enable: true
    namespaces: application
env: DEV

#mybatis-plus配置sql语句日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#spring 配置
spring:
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
  #spring security 用户名和密码
  security:
    user:
      name: root
      password: root