#自定义配置
person:
  name: chendong
  age: 27
  lists: [ cat,dog,person ]
  lists1:
    - cat
    - dog
    - person
  maps: { k1: v1,k2: v2 }
  dog:
    name: xiaohuang

#apollo配置
app:
  id: demo-9527
apollo:
  meta: http://10.29.60.125:8080
  bootstrap:
    enable: true
    namespaces: application
env: DEV

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis配置
mybatis:
  type-aliases-package: com.chendong.demo.core
  mapper-locations: classpath:mapper/*Mapper.xml
  #驼峰映射
  configuration:
    map-underscore-to-camel-case: true

spring:
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
  #spring security 用户名和密码
  security:
    user:
      name: root
      password: root

---
#开发环境配置
server:
  port: 9081
spring:
  profiles: dev

---
#测试环境配置
server:
  port: 8082
spring:
  profiles: test